= Neo4j Browser =

*Explore the graph, one query at a time.*

Neo4j Browser is http://github.com/neo4j/neo4j/[Neo4j's] built-in client application, a mashup of a REPL, data visualization and lightweight IDE.

== Installation ==

The program will require JDK, Maven, Node.JS and NPM installed.

 * Install http://openjdk.java.net/[JKD]

```
# Update apt-get cache
sudo apt-get update

# (Optional) Check the packages avaliable
apt-cache search JDK

# Install JDK 1.7
sudo apt-get install openjdk-7-jdk

# (Optional) Check the Java version
java -version
```

 * Install https://maven.apache.org/[Maven]

```
# Install the package
sudo apt-get install maven

# (Optional) Check the Maven version
mvn -version
```

 * Install https://nodejs.org/[Node.JS]

```
# (Optional) Remove old Node installations, if they exist
sudo apt-get --purge remove node
sudo apt-get --purge remove nodejs

# Install the package
sudo apt-get install nodejs

# Add symlink to the node
sudo ln -s /usr/bin/nodejs /usr/bin/node

# (Optional) Check the Node.JS version
node --version
```

 * Install https://www.npmjs.com/[NPM]

```
# Install NPM
sudo apt-get install npm

# Install Grunt Client
sudo npm install -g grunt-cli

# Install Bower
sudo npm install -g bower

# Install NPM modules 
cd browser && npm install

# (Optional) Check the NPM version
npm -version
```

== Goals ==

* developer focused
* every interaction is a demonstration
* uses only public APIs
* for modern browsers, with reasonable fallbacks

== Development ==

Set up your environment::

  * Install https://nodejs.org/[node.js]
  * `cd community/browser && npm install`
+
This installs npm modules needed to build the browser code.
  * `npm install -g grunt-cli`
+
This puts the `grunt` command on your path.

Run in development mode::

  * Run Neo4j server (from a downloaded distribution of Neo4j, or from your IDE)
  * `cd community/browser` (this directory in the source tree)
  * `grunt server`
+
This listens on port 9000, serving up static documents, and forwarding other requests to Neo4j on port 7474. 
Any local changes to the browser code will be applied immediatley by reloading the page.

== Feedback ==

* mailto:andreas@neotechnology.com[Andreas Kollegger] - questions or comments? send an email to me

== Adding a new Cypher keyword ==

Look at:

* Detecting Cypher: app/scripts/init/commandInterpreters.coffee
* app/components/cypher/index.js
* app/scripts/codemirror-cypher.coffee
