= Neo4j Browser =

*Explore the graph, one query at a time.*

Neo4j Browser is http://github.com/neo4j/neo4j/[Neo4j's] built-in client application, a mashup of a REPL, data visualization and lightweight IDE.

== Installation ==

The program will require JDK, Maven, Node.JS and NPM installed.

 * Install http://openjdk.java.net/[JKD]

```
# Update apt-get cache
sudo apt-get update

# (Optional) Check the packages avaliable
apt-cache search JDK

# Install JDK 1.7
sudo apt-get install openjdk-7-jdk

# (Optional) Check the Java version
java -version
```

 * Install https://maven.apache.org/[Maven]

```
# Install the package
sudo apt-get install maven

# (Optional) Check the Maven version
mvn -version
```

 * Install https://nodejs.org/[Node.JS]

```
# (Optional) Remove old Node installations, if they exist
sudo apt-get --purge remove node
sudo apt-get --purge remove nodejs

# Install the package
sudo apt-get install nodejs

# Add symlink to the node
sudo ln -s /usr/bin/nodejs /usr/bin/node

# (Optional) Check the Node.JS version
node --version
```

 * Install https://www.npmjs.com/[NPM]

```
# Install NPM
sudo apt-get install npm

# Install Grunt Client
sudo npm install -g grunt-cli

# Install Bower
sudo npm install -g bower

# Install NPM modules 
cd browser && npm install

# (Optional) Check the NPM version
npm -version
```

== Build ==

To build the project, execute `mvn clean package` or `mvn clean install`. The compiled jar file will be availiable in the target folder

== Offline Build ==

To build the project offline (for example on another machine), build the project once, then transfer the project folder and .m2 folder from your home directory into new machine.

Execute `mvn -o package` or `mvn -o install` for the offline build.

== Run in development mode ==

Run in development mode::

  * Run Neo4j server (from a downloaded distribution of Neo4j, or from your IDE)
  * `cd community/browser` (this directory in the source tree)
  * `grunt server`
+
This listens on port 9000, serving up static documents, and forwarding other requests to Neo4j on port 7474. 
Any local changes to the browser code will be applied immediatley by reloading the page.

== Feedback ==

* mailto:andreas@neotechnology.com[Andreas Kollegger] - questions or comments? send an email to me

== Adding a new Cypher keyword ==

Look at:

* Detecting Cypher: app/scripts/init/commandInterpreters.coffee
* app/components/cypher/index.js
* app/scripts/codemirror-cypher.coffee
